foomo/helm-charts

- charts/namespace/Chart.yaml
- charts/namespace/README.md
- charts/namespace/examples/k9s.yaml
- charts/namespace/templates/clusterrole.yaml
- charts/namespace/templates/rolebinding.yaml
- charts/namespace/values.schema.json
- charts/namespace/values.yaml
Ability to create cluster roles and role bindings
> Namespace v0.2.3

- .github/dependabot.yml
- README.md
- charts/sesamy-gtm/Chart.yaml
- charts/sesamy-gtm/README.md
- charts/sesamy-gtm/values.schema.json
- charts/sesamy-gtm/values.yaml
Adds additional `/_/service_worker` route
> fix(sesamy gtm): add service worker route

- charts/squadron-keel-cronjob/Chart.yaml
- charts/squadron-keel-cronjob/README.md
- charts/squadron-keel-cronjob/templates/cronjob.yaml
- charts/squadron-keel-cronjob/values.schema.json
- charts/squadron-keel-cronjob/values.yaml
- charts/squadron-keel-server/Chart.yaml
- charts/squadron-keel-server/README.md
- charts/squadron-keel-server/templates/deployment.yaml
- charts/squadron-keel-server/values.schema.json
- charts/squadron-keel-server/values.yaml
- charts/squadron-nextjs-server/Chart.yaml
- charts/squadron-nextjs-server/README.md
- charts/squadron-nextjs-server/templates/deployment.yaml
- charts/squadron-nextjs-server/values.schema.json
- charts/squadron-nextjs-server/values.yaml
- charts/squadron-server/Chart.yaml
- charts/squadron-server/README.md
- charts/squadron-server/templates/deployment.yaml
- charts/squadron-server/values.schema.json
- charts/squadron-server/values.yaml
- add init and sidecar containers
> feat: add init and sidecar containers

- charts/contentserver/Chart.yaml
- charts/contentserver/README.md
- charts/contentserver/templates/_helpers.tpl
- charts/squadron-keel-cronjob/Chart.yaml
- charts/squadron-keel-cronjob/README.md
- charts/squadron-keel-cronjob/templates/_helpers.tpl
- charts/squadron-keel-server/Chart.yaml
- charts/squadron-keel-server/README.md
- charts/squadron-keel-server/templates/_helpers.tpl
- charts/squadron-nextjs-server/Chart.yaml
- charts/squadron-nextjs-server/README.md
- charts/squadron-nextjs-server/templates/_helpers.tpl
Use release name instead of full name
> fix: otel service name

- charts/namespace/Chart.yaml
- charts/namespace/README.md
- charts/namespace/templates/_helpers.tpl
- charts/squadron-keel-cronjob/Chart.yaml
- charts/squadron-keel-cronjob/README.md
- charts/squadron-keel-cronjob/templates/_helpers.tpl
- charts/squadron-keel-cronjob/values.schema.json
- charts/squadron-keel-cronjob/values.yaml
- charts/squadron-keel-server/Chart.yaml
- charts/squadron-keel-server/README.md
- charts/squadron-keel-server/templates/_helpers.tpl
- charts/squadron-keel-server/values.schema.json
- charts/squadron-keel-server/values.yaml
- charts/squadron-nextjs-server/Chart.yaml
- charts/squadron-nextjs-server/README.md
- charts/squadron-nextjs-server/templates/_helpers.tpl
- charts/squadron-nextjs-server/values.schema.json
- charts/squadron-nextjs-server/values.yaml
- charts/squadron-server/Chart.yaml
- charts/squadron-server/README.md
- charts/squadron-server/templates/_helpers.tpl
- charts/squadron-server/values.schema.json
- charts/squadron-server/values.yaml
Use `.Release.Name` as label selector and provide `withDeprecatedSelectorLabelsV2` for backward compatibility
> feature: label selector

- charts/sesamy-gtm/Chart.yaml
- charts/sesamy-gtm/README.md
- charts/sesamy-gtm/values.schema.json
- charts/sesamy-gtm/values.yaml
Use ImplementationSpecific ingress type
> fix(sesamy-gtm): use ImplementationSpecific

- charts/sesamy-gtm/Chart.yaml
- charts/sesamy-gtm/README.md
> fix(sesamy-gtm): fix version

- charts/squadron-nextjs-server/Chart.yaml
- charts/squadron-nextjs-server/README.md
- charts/squadron-nextjs-server/templates/ingress.yaml
Use `ImplementationSpecfic` pathType
> fix(squadron-nextjs-server): ingress pathType

- charts/sesamy-umami/Chart.yaml
- charts/sesamy-umami/README.md
- charts/sesamy-umami/values.schema.json
- charts/sesamy-umami/values.yaml
> fix(sesamy-umami): hosts type

- charts/namespace/Chart.yaml
- charts/namespace/README.md
- charts/namespace/templates/clusterrole.yaml
- charts/namespace/templates/clusterrolebinding.yaml
- charts/namespace/values.schema.json
- charts/namespace/values.yaml
- [feat(namespace): add cluster role bindings](https://github.com/foomo/helm-charts/commit/1d7d84c63a608c7d69037d680adda663a19aee58)
> feat(namespace): add cluster role bindings

- charts/beam/Chart.yaml
- charts/beam/README.md
- charts/beam/values.schema.json
- charts/beam/values.yaml
- bump pinniped
- bump cloudflared
> feat(beam): bump deps

- charts/contentserver/Chart.yaml
- charts/contentserver/README.md
- charts/contentserver/values.schema.json
- charts/contentserver/values.yaml
- Contentserver [v1.12.0](https://github.com/foomo/contentserver/releases/tag/v1.12.0)
> feat(contentserver): v1.12.0

- Makefile
- charts/backups/templates/cronjob.yaml
- charts/squadron-cronjob/.helmignore
- charts/squadron-cronjob/Chart.yaml
- charts/squadron-cronjob/README.md
- charts/squadron-cronjob/README.md.gotmpl
- charts/squadron-cronjob/templates/_helpers.tpl
- charts/squadron-cronjob/templates/cronjob.yaml
- charts/squadron-cronjob/templates/networkpolicy.yaml
- charts/squadron-cronjob/templates/persistentvolumeclaim.yaml
- charts/squadron-cronjob/templates/secret.yaml
- charts/squadron-cronjob/templates/serviceaccount.yaml
- charts/squadron-cronjob/templates/validate.yaml
- charts/squadron-cronjob/values.schema.json
- charts/squadron-cronjob/values.yaml
- charts/squadron-keel-cronjob/Chart.yaml
- charts/squadron-keel-cronjob/README.md
- charts/squadron-keel-cronjob/values.schema.json
- charts/squadron-keel-cronjob/values.yaml
> feat: add chart squadron-cronjob

- charts/squadron-cronjob/Chart.yaml
- charts/squadron-cronjob/README.md
- charts/squadron-cronjob/templates/cronjob.yaml
> fix(squadron-cronjob): indention

- charts/contentserver/Chart.yaml
- charts/contentserver/README.md
- charts/contentserver/templates/statefulset.yaml
- charts/contentserver/values.schema.json
- charts/contentserver/values.yaml
- charts/squadron-cronjob/Chart.yaml
- charts/squadron-cronjob/README.md
- charts/squadron-cronjob/templates/cronjob.yaml
- charts/squadron-cronjob/values.schema.json
- charts/squadron-cronjob/values.yaml
- charts/squadron-keel-cronjob/Chart.yaml
- charts/squadron-keel-cronjob/README.md
- charts/squadron-keel-cronjob/templates/cronjob.yaml
- charts/squadron-keel-cronjob/values.schema.json
- charts/squadron-keel-cronjob/values.yaml
- charts/squadron-keel-server/Chart.yaml
- charts/squadron-keel-server/README.md
- charts/squadron-keel-server/templates/deployment.yaml
- charts/squadron-keel-server/values.schema.json
- charts/squadron-keel-server/values.yaml
- charts/squadron-nextjs-server/Chart.yaml
- charts/squadron-nextjs-server/README.md
- charts/squadron-nextjs-server/templates/deployment.yaml
- charts/squadron-nextjs-server/values.schema.json
- charts/squadron-nextjs-server/values.yaml
- charts/squadron-server/Chart.yaml
- charts/squadron-server/README.md
- charts/squadron-server/templates/deployment.yaml
- charts/squadron-server/values.schema.json
- charts/squadron-server/values.yaml
- add container security context
> fix: add container security context

- .gitignore
- .ownbrew.yaml
- Makefile
- charts/squadron-cronjob/Chart.yaml
- charts/squadron-cronjob/README.md
- charts/squadron-cronjob/templates/cronjob.yaml
- charts/squadron-keel-cronjob/Chart.yaml
- charts/squadron-keel-cronjob/README.md
- charts/squadron-keel-cronjob/templates/cronjob.yaml
- charts/squadron-keel-server/Chart.yaml
- charts/squadron-keel-server/README.md
- charts/squadron-keel-server/templates/deployment.yaml
> fix: value access

- charts/contentserver/Chart.yaml
- charts/contentserver/README.md
- charts/contentserver/values.schema.json
- charts/contentserver/values.yaml
- charts/squadron-cronjob/Chart.yaml
- charts/squadron-cronjob/README.md
- charts/squadron-cronjob/values.schema.json
- charts/squadron-cronjob/values.yaml
- charts/squadron-keel-cronjob/Chart.yaml
- charts/squadron-keel-cronjob/README.md
- charts/squadron-keel-cronjob/values.schema.json
- charts/squadron-keel-cronjob/values.yaml
- charts/squadron-keel-server/Chart.yaml
- charts/squadron-keel-server/README.md
- charts/squadron-keel-server/values.schema.json
- charts/squadron-keel-server/values.yaml
- charts/squadron-nextjs-server/Chart.yaml
- charts/squadron-nextjs-server/README.md
- charts/squadron-nextjs-server/values.schema.json
- charts/squadron-nextjs-server/values.yaml
- charts/squadron-server/Chart.yaml
- charts/squadron-server/README.md
- charts/squadron-server/values.schema.json
- charts/squadron-server/values.yaml
Set `seccompProfile` & `capabilities`
> feat: set seccompProfile & capabilities

- charts/squadron-keel-server/Chart.yaml
- charts/squadron-keel-server/README.md
- charts/squadron-keel-server/templates/_helpers.tpl
- charts/squadron-keel-server/templates/deployment.yaml
- charts/squadron-keel-server/values.schema.json
- charts/squadron-keel-server/values.yaml
Make keel services configurable
> feat(squadron-keel-server): configure keel services

- charts/beam/Chart.yaml
- charts/beam/README.md
- charts/beam/values.schema.json
- charts/beam/values.yaml
- pinniped 2.4.17
- cloudflared 2025.5.0
> feat(beam): update deps

- charts/contentserver/Chart.yaml
- charts/contentserver/README.md
- charts/contentserver/values.schema.json
- charts/contentserver/values.yaml
Bump contentserver version
_[If this pull request addresses an issue, please link to it here (e.g., Fixes #123).]_
> contentserver 0.6.4

- charts/squadron-cronjob/Chart.yaml
- charts/squadron-cronjob/README.md
- charts/squadron-cronjob/templates/_helpers.tpl
- charts/squadron-cronjob/values.schema.json
- charts/squadron-cronjob/values.yaml
- charts/squadron-keel-cronjob/Chart.yaml
- charts/squadron-keel-cronjob/README.md
- charts/squadron-keel-cronjob/templates/_helpers.tpl
- charts/squadron-keel-cronjob/values.schema.json
- charts/squadron-keel-cronjob/values.yaml
- charts/squadron-keel-server/Chart.yaml
- charts/squadron-keel-server/README.md
- charts/squadron-keel-server/templates/_helpers.tpl
- charts/squadron-keel-server/values.schema.json
- charts/squadron-keel-server/values.yaml
- charts/squadron-nextjs-server/Chart.yaml
- charts/squadron-nextjs-server/README.md
- charts/squadron-nextjs-server/templates/_helpers.tpl
- charts/squadron-nextjs-server/values.schema.json
- charts/squadron-nextjs-server/values.yaml
- charts/squadron-server/Chart.yaml
- charts/squadron-server/README.md
- charts/squadron-server/templates/_helpers.tpl
- charts/squadron-server/values.schema.json
- charts/squadron-server/values.yaml
- add optional labels override for backward compatibility
> feat: add labels override

- charts/squadron-cronjob/Chart.yaml
- charts/squadron-cronjob/README.md
- charts/squadron-cronjob/templates/_helpers.tpl
- charts/squadron-cronjob/templates/cronjob.yaml
- charts/squadron-keel-cronjob/Chart.yaml
- charts/squadron-keel-cronjob/README.md
- charts/squadron-keel-cronjob/templates/_helpers.tpl
- charts/squadron-keel-cronjob/templates/cronjob.yaml
- charts/squadron-keel-server/Chart.yaml
- charts/squadron-keel-server/README.md
- charts/squadron-keel-server/templates/_helpers.tpl
- charts/squadron-keel-server/templates/deployment.yaml
- charts/squadron-nextjs-server/Chart.yaml
- charts/squadron-nextjs-server/README.md
- charts/squadron-nextjs-server/templates/_helpers.tpl
- charts/squadron-nextjs-server/templates/deployment.yaml
- charts/squadron-server/Chart.yaml
- charts/squadron-server/README.md
- charts/squadron-server/templates/_helpers.tpl
- charts/squadron-server/templates/deployment.yaml
- use overrides in template labels
> fix: use override in selector labels
